### ISSUE TITLE
Code Review #1

### ISSUE THREAD

**Issue by bigman212** [koshmark/Calc#1]
1. Добавляй файлы не через сайт, а через консоль/Visual Studio.
2. Куча каких-то ненужных и сгенерированных VS файлов. Убрать.
3. Фигурные скобки переносятся на новую строчку только в исключительных случаях.
https://github.com/koshmark/Calc/blob/3d4042f88b89bdc39c6a706c0381c88d6cd24ddf/Calc.cpp#L9
4. Сколько у тебя стоит отступ?? Максимум два-четыре пробела.
https://github.com/koshmark/Calc/blob/3d4042f88b89bdc39c6a706c0381c88d6cd24ddf/Calc.cpp#L10
5. Num1 Num2? Подключи фантазию - назови как-нибудь более понятно. Вычитаемое, слагаемое, как-нибудь по математически.
6. Починить exit
### DRY (dont repeat yourself)
7. cin >> num1 >> num2 можно вынести за пределы switch. Этот участок кода повторяется, плохо.
8. cout << ... также повторяется. Вынести в функцию. 
https://github.com/koshmark/Calc/blob/3d4042f88b89bdc39c6a706c0381c88d6cd24ddf/Calc.cpp#L40

**Comment by koshmark** [comment]
Я всё исправил, точнее Глеб(Марк)
